Start onboarding feature
RefBuddy/ref-buddy-web pull request #63
Opened 2024-01-15 02:30 UTC by jonahduckworth

- new admin route
- tables for officials and supervisors
- delete button works
     - confirmation modal opens
          - abstracted `ConfirmationModal` from `SelectedGames`
     - dispatch `deleteUser` on confirm, then: dispatch `getOfficialsList`, close modal, turn off loading, and show success toast

### LOG IN TO AJHL LEAGUE TO TEST
- email: admin@ajhl.ca
- password: password
- delete either of the accounts that are there

<img width="1728" alt="Screenshot 2024-01-14 at 7 18 42 PM" src="https://github.com/RefBuddy/ref-buddy-web/assets/35585020/cb003310-67cc-40b5-9ea2-1d3f28f9e34d">

Follow up PR will include inviting user feature

2024-01-30 22:18 UTC, rymccue commented on src/components/Calendar/SelectedGames/SelectedGames.tsx
> +                <ConfirmationModal
This is clean 👌

2024-01-30 22:29 UTC, rymccue commented on src/templates/Admin/Admin.tsx
> +  const [uid, deleteUid] = useState<string>('');
This doesn't really delete the uid, does it?

2024-01-30 22:30 UTC, rymccue commented on src/templates/Admin/components/InviteUserModal.tsx
> +    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
Is this a proper email regex? Looks smaller than I've seen before but might this is just cleaner!

2024-01-30 22:32 UTC, rymccue requested changes
Added a few comments, overall this is awesome though!! 🔥

2024-01-30 22:51 UTC, jonahduckworth commented on src/templates/Admin/Admin.tsx
> +  const [uid, deleteUid] = useState<string>('');
would `const [deleteUid, setDeleteUid] = useState<string>('');` make more sense?

2024-01-30 22:51 UTC, jonahduckworth commented on src/templates/Admin/components/InviteUserModal.tsx
> +    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
[chatGPT's response](https://chat.openai.com/share/4d882488-4c16-4888-b34e-347dffbf3db7)

tl;dr this regex asserts something@something.something

2024-01-31 00:25 UTC, rymccue commented on src/templates/Admin/Admin.tsx
> +  const [uid, deleteUid] = useState<string>('');
What about `const [uidToDelete, setUidToDelete] = useState<string>('');`? It explains it a bit more.

2024-01-31 00:28 UTC, rymccue commented on src/templates/Admin/components/InviteUserModal.tsx
> +    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
Oh nice, yeah and that works with `ryan+test@ryanmccue.ca` which I didn't expect

2024-01-31 00:28 UTC, rymccue approved these changes

2024-02-02 01:52 UTC, merged